const GAME_DETAILS = {
  'SFV': {
    fullName: "Street Fighter V",
    abbrName: "SFV",
    characterList: [
      "Abigail",
      "Akuma",
      "Alex",
      "Balrog",
      "Birdie",
      "Blanka",
      "Cammy",
      "Chun-Li",
      "Cody",
      "Dan",
      "Dhalsim",
      "E.Honda",
      "Ed",
      "Falke",
      "F.A.N.G",
      "G",
      "Gill",
      "Guile",
      "Ibuki",
      "Juri",
      "Kage",
      "Karin",
      "Ken",
      "Kolin",
      "Laura",
      "Lucia",
      "M.Bison",
      "Menat",
      "Nash",
      "Necalli",
      "Poison",
      "Rashid",
      "R.Mika",
      "Ryu",
      "Sagat",
      "Sakura",
      "Seth",
      "Urien",
      "Vega",
      "Zangief",
      "Zeku",
    ],
  },
  'USF4': {
    fullName: "Ultra Street Fighter 4",
    abbrName: "USF4",
    characterList: [
      "Abel",
      "Adon",
      "Akuma",
      "Balrog",
      "Blanka",
      "C.Viper",
      "Cammy",
      "Chun-Li",
      "Cody",
      "Dan",
      "Decapre",
      "Dee Jay",
      "Dhalsim",
      "Dudley",
      "E.Honda",
      "Elena",
      "El Fuerte",
      "Evil Ryu",
      "Fei Long",
      "Gen",
      "Gouken",
      "Guile",
      "Guy",
      "Hakan",
      "Hugo",
      "Ibuki",
      "Juri",
      "Ken",
      "M.Bison",
      "Makoto",
      "Oni",
      "Poison",
      "Rolento",
      "Rose",
      "Rufus",
      "Ryu",
      "Sagat",
      "Sakura",
      "Seth",
      "T.Hawk",
      "Vega",
      "Yang",
      "Yun",
      "Zangief"
    ],
  },
  '3S': {
    fullName: "Street Fighter 3: Third Strike",
    abbrName: "3S",
    characterList: [
      "Alex",
      "Akuma",
      "Chun-Li",
      "Dudley",
      "Elena",
      "Hugo",
      "Ibuki",
      "Ken",
      "Makoto",
      "Necro",
      "Oro",
      "Q",
      "Remy",
      "Ryu",
      "Sean",
      "Twelve",
      "Urien",
      "Yang",
      "Yun"
    ],
  },
};

module.exports = GAME_DETAILS;